server:
  port: 8889
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bishe_date?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /templates
      suffix: .html



mybatis-plus:
  type-aliases-package: com.demo.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



